WatchStore/Controllers/NguoidungController.cs
using System;
using System.Data;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using WatchStore.Models;
using System.Data.SqlClient;
using Facebook;
using System.Configuration;
using System.Text.RegularExpressions;




namespace WatchStore.Controllers
{
    public class NguoidungController : Controller
    {
        dbQLBandhDataContext data = new dbQLBandhDataContext();

        private Uri RedirectUri
        {
            get
            {
                var uriBuilder = new UriBuilder(Request.Url);
                uriBuilder.Query = null;
                uriBuilder.Fragment = null;
                uriBuilder.Path = Url.Action("FacebookCallback");
                return uriBuilder.Uri;
            }
        }
        // GET: Nguoidung

        public ActionResult Index()
        {
            return View();
        }
        [HttpGet]

        public ActionResult Dangky()
        {
            return View();
        }
        [HttpPost]

        public ActionResult Dangky(FormCollection collection, KHACHHANG kh)
        {
            var hoten = collection["HoTenKH"];
            var tendn = collection["TenDN"];
            var matkhau = collection["Matkhau"];
            var matkhaunhaplai = collection["Matkhaunhaplai"];
            var diachi = collection["Diachi"];
            var email = collection["Email"];
            var dienthoai = collection["Dienthoai"];
            var ngaysinh = String.Format("{0:yyyy/MM/dd}", collection["Ngaysinh"]);
            if (matkhau != matkhaunhaplai)
            {
                ViewData["Loi1"] = "không trùng mật khẩu!";
            }
            else
            {
                kh.HoTen = hoten;
                kh.Taikhoan = tendn;
                kh.Matkhau = matkhau;
                kh.Email = email;
                kh.DiachiKH = diachi;
                kh.DienthoaiKH = dienthoai;
                kh.Ngaysinh = DateTime.Parse(ngaysinh);
                data.KHACHHANGs.InsertOnSubmit(kh);
                data.SubmitChanges();
                ViewBag.Thongbao = "Đăng ký thành công";

                return RedirectToAction("Dangnhap");
            }

            return this.Dangky();

        }
        [HttpGet]
        public ActionResult Dangnhap()
        {
            return View();
        }
        [HttpPost]

        public ActionResult Dangnhap(FormCollection collection)
        {
            var tendn = collection["TenDN"].ToString();
            var matkhau = collection["Matkhau"].ToString();
            KHACHHANG kh = data.KHACHHANGs.SingleOrDefault(n => n.Taikhoan == tendn && n.Matkhau == matkhau);
            ViewBag.MaKH = kh.MaKH;

            if (kh != null)
            {
                Session["Taikhoan"] = kh;
                Session["TenDN"] = kh.HoTen;
                return RedirectToAction("Index", "WatchStore");
            }
            ViewBag.Thongbao = "Tên đăng nhập hoặc mật khẩu không đúng";
            return View();
        }
        public ActionResult DangXuat()
        {
            Session.Abandon();
            FormsAuthentication.SignOut();
            return RedirectToAction("Dangnhap");
        }

        public ActionResult HienThiKH(int makh)
        {

            //Lấy ra đối tượng kh theo mã
            KHACHHANG kh = data.KHACHHANGs.SingleOrDefault(n => n.MaKH == makh);
            Session["Taikhoan"] = kh;
            Session["MaKH"] = kh.MaKH;
            if (kh == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            return View(kh);
        }
  
    }
}

WatchStore/Views/Nguoidung/Dangky.cshtml
@model IEnumerable<WatchStore.Models.KHACHHANG>
@{
    ViewBag.Title = "Đăng ký    ";
    Layout = "~/Views/Shared/_LayoutUser.cshtml";
}
<div class="banner_inner">
    <div class="services-breadcrumb">
        <div class="inner_breadcrumb">
            <ul class="short">
                <li>
                    @Html.ActionLink("Trang Chủ", "Index", "WatchStore")
                    <i style="color:black">|</i>
                    @Html.ActionLink("Đăng ký", "Dangky", "Nguoidung")
                </li>
                <li>Đăng ký thành viên</li>
            </ul>
        </div>
    </div>
</div>
<!--//banner -->

<h3 class="tittle-w3layouts text-center my-lg-4 my-4">Đăng ký thành viên</h3>
<div class="alert alert-danger alert-dismissible" role="alert" style="text-align:center ">
    <strong>@ViewBag.Thongbao</strong>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>
<hr>
<section class="banner-bottom-wthreelayouts py-lg-5 py-3">

    <div class="container">
        <div class="inner_sec">
            <div class="contact_grid_right">
                @using (Html.BeginForm())
                {
                    @Html.ValidationSummary(true)
                    <div class="row contact_left_grid">
                        <div class="col-md-6 con-left">
                            <div class="form-group">
                                <label class="my-2">Họ tên </label>
                                <input class="form-control" type="text" name="HotenKH" placeholder="Nhập họ tên..." required="">
                            </div>
                            <div class="form-group">
                                <label class="my-2">Email / Tên đăng nhập </label>
                                <input class="form-control" type="email" name="TenDN" placeholder="Nhập email / tên đăng nhập..." required="">
                            </div>
                            <div class="form-group">
                                <label class="my-2">Mật khẩu:</label>
                                <input class="form-control" type="password" name="Matkhau" placeholder="Nhập mật khẩu..." required="" style="outline: none;padding: 15px 15px;font-size: 14px;color: #777;background: #f7f7f7;width: 100%;letter-spacing: 1px;border: 1px solid #ebeeef;">
                            </div>
                            <div class="form-group">
                                <label class="my-2">Nhập lại mật khẩu:</label>
                                <input class="form-control" placeholder="Nhập lại mật khẩu..." name="Matkhaunhaplai" type="password" required="" style="outline: none;padding: 15px 15px;font-size: 14px;color: #777;background: #f7f7f7;width: 100%;letter-spacing: 1px;border: 1px solid #ebeeef;">
                                @ViewData["Loi1"]
                            </div>
                        </div>
                        <div class="col-md-6 con-right">
                            <div class="form-group">
                                <label class="my-2">Email:</label>
                                <input class="form-control" placeholder="Nhập Email..." name="Email" type="email" required="">
                            </div>
                            <div class="form-group">
                                <label class="my-2">Số điện thoại:</label>
                                <input class="form-control" placeholder="Nhập sđt..." name="Dienthoai" type="tel" required="" style="outline: none;padding: 15px 15px;font-size: 14px;color: #777;background: #f7f7f7;width: 100%;letter-spacing: 1px;border: 1px solid #ebeeef;">
                            </div>
                            <div class="form-group">
                                <label class="my-2">Ngày sinh:</label>
                                <input class="form-control" type="date" name="Ngaysinh" style="outline: none;padding: 15px 15px;font-size: 14px;color: #777;background: #f7f7f7;width: 100%;letter-spacing: 1px;border: 1px solid #ebeeef;" />
                            </div>
                            <div class="form-group">
                                <label class="my-2">Địa chỉ:</label>
                                <input class="form-control" placeholder="Nhập địa chỉ..." type="text" name="Diachi" style="outline: none;padding: 15px 15px;font-size: 14px;color: #777;background: #f7f7f7;width: 100%;letter-spacing: 1px;border: 1px solid #ebeeef;" required="" />
                            </div>
                        </div>
                    </div>
                    <br />
                    <input class="form-control" type="submit" value="Đăng ký" />
                }

            </div>
        </div>
    </div>
</section>
<hr>
<script>
    $(document).ready(function () {
        $('#dataTables-example').DataTable({
            responsive: true
        });
    });
</script>

WatchStore/Views/Nguoidung/Dangnhap.cshtml
@model WatchStore.Models.KHACHHANG
@using WatchStore.Models
@{
    ViewBag.Title = "Đăng nhập";
    Layout = "~/Views/Shared/_LayoutUser.cshtml";
}
<div class="banner_inner">
    <div class="services-breadcrumb">
        <div class="inner_breadcrumb">

            <ul class="short">
                <li>
                    @Html.ActionLink("Trang Chủ", "Index", "WatchStore")
                    <i style="color:black">|</i>
                    @Html.ActionLink("Đăng nhập tài khoản", "Dangnhap", "Nguoidung")
                </li>

            </ul>
        </div>
    </div>

</div>
<!--//banner -->

<h3 class="tittle-w3layouts text-center my-lg-4 my-4">Đăng nhập tài khoản</h3>


<div class="alert alert-danger alert-dismissible" role="alert" style="text-align:center ">
    <strong>@ViewBag.Thongbao</strong>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>

<hr />
<section class="banner-bottom-wthreelayouts py-lg-5 py-3">
    <div class="container">
        <div class="inner_sec">
            <div class="contact_grid_right">

                @using (Html.BeginForm())
                {
                    @Html.ValidationSummary(true)
                    <div class="row contact_left_grid">
                        <div class="col-md-3">

                        </div>
                        <div class="col-md-6 ">
                            <div class="form-group">
                                <label class="my-2">Email/Tài khoản</label>
                                <input name="TenDN" type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="" required="">
                            </div>
                            <div class="form-group">
                                <label class="my-2">Mật khẩu</label>
                                <input name="Matkhau" type="password" class="form-control" id="exampleInputPassword1" placeholder="" required="" style="outline: none;padding: 15px 15px;font-size: 14px;color: #777;background: #f7f7f7;width: 100%;letter-spacing: 1px;border: 1px solid #ebeeef;">
                            </div>
                            <input class="form-control" type="submit" value="Đăng nhập" />
                            <br />
                            <div class="fb-login-button" data-size="large" data-button-type="login_with" data-auto-logout-link="true" data-use-continue-as="true"></div>
                            <div id="status">
                            </div>
                            <br />
                            <div class="req_pass" style="text-align:center">
                                Bạn chưa có tài khoản
                                <span>|</span>
                                @Html.ActionLink("Đăng ký ngay", "DangKy", "Nguoidung")
                            </div>
                        </div>
                    </div>
                    <div class="col-md-3">
                    </div>
                    <!---->
                }
            </div>
        </div>
    </div>
</section>
<hr />

<script src="~/Scripts/FacebookLogin.js"></script>
<div id="fb-root"></div>
<script async defer crossorigin="anonymous" src="https://connect.facebook.net/vi_VN/sdk.js#xfbml=1&version=v3.2&appId=817732121913685&autoLogAppEvents=1"></script>

<script>
    $(document).ready(function () {
        $('#dataTables-example').DataTable({
            responsive: true
        });
    });
</script>

WatchStore/Views/Nguoidung/HienThiKH.cshtml
@model WatchStore.Models.KHACHHANG

@{
    ViewBag.Title = "HienThiKH";
    Layout = "~/Views/Shared/_LayoutUser.cshtml";
}

<h2>HienThiKH</h2>

<div>
    <h4>KHACHHANG</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.HoTen)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.HoTen)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Taikhoan)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Taikhoan)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Matkhau)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Matkhau)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DiachiKH)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DiachiKH)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DienthoaiKH)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DienthoaiKH)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Ngaysinh)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Ngaysinh)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.MaKH }) |
    @Html.ActionLink("Back to List", "Index")
</p>