WatchStore/Areas/Admin/Controllers/AuthhController.cs
using System;
using System.Collections.Generic;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using WatchStore.Areas.Admin.Models;
using WatchStore.Models;

namespace WatchStore.Areas.Admin.Controllers
{
    public class AuthhController : Controller
    {
        dbQLBandhDataContext db = new dbQLBandhDataContext();

        // GET: Admin/Authh

       
        public ActionResult kCoQuyen()
        {
            return View();
        }
        [HttpGet]
        public ActionResult Login()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Login(FormCollection f, LoginViewModel model)
        {  
            var TK = f["username"];
            var MK = f["password"];
            var ad = db.ADMINs.SingleOrDefault(n => n.UserAdmin == TK && n.PassAdmin  == MK);
            if (ad != null)
            {
              
                ViewBag.ThongBao = "Xin chào, Admin:" + ad.Hoten;
                FormsAuthentication.SetAuthCookie(ad.Hoten, false);
                Session["TaiKhoanAdmin"] = ad;
                Session["Admin"] = ad.UserAdmin;
                Session["Pw"] = ad.PassAdmin;
                return RedirectToAction("Index", "ThongKe");
            }
            ViewBag.ThongBao = "Tên tài khoản hoặc mật khẩu không đúng!!!";
            TempData["thongbao"] = "Không tìm thấy khách hàng nào phù hợp.";
            return View();
        }
        public ActionResult Logout()
        {
            Session.Abandon();
            FormsAuthentication.SignOut();
            return RedirectToAction("Login");
        }

    }
}

WatchStore/Areas/Admin/Controllers/QlyKhachHangController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList;
using PagedList.Mvc;
using WatchStore.Models;

namespace WatchStore.Areas.Admin.Controllers
{
    public class QlyKhachHangController : Controller
    {
        dbQLBandhDataContext db = new dbQLBandhDataContext();
        // GET: Admin/QlyKhachHang
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult DanhSachKhachHang(string timkiem, int? page)
        {
            if (Session["Admin"] == null || Session["TaiKhoanAdmin"].ToString() == "")
            {
                return RedirectToAction("Login", "Authh");
            }
            ViewBag.TuKhoa = timkiem;
            int pageNumber = (page ?? 1);
            int pageSize = 5;
            if (timkiem != null)
            {
                List<KHACHHANG> listKQ = db.KHACHHANGs.Where(n => n.HoTen.Contains(timkiem)).ToList();
                if (listKQ.Count == 0)
                {
                    TempData["thongbao"] = "Không tìm thấy khách hàng nào phù hợp.";
                    return View(db.KHACHHANGs.OrderBy(n => n.HoTen).ToPagedList(pageNumber, pageSize));
                }
                return View(listKQ.OrderBy(n => n.HoTen).ToPagedList(pageNumber, pageSize));
            }
            return View(db.KHACHHANGs.OrderBy(n => n.HoTen).ToPagedList(pageNumber, pageSize));
        }

        //Chi tiết
        public ActionResult HienThiKH(int makh)
        {
            if (Session["Admin"] == null || Session["TaiKhoanAdmin"].ToString() == "")
            {
                return RedirectToAction("Login", "Authh");
            }
            //Lấy ra đối tượng sp theo mã
            KHACHHANG kh = db.KHACHHANGs.SingleOrDefault(n => n.MaKH == makh);
            if (kh == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            return View(kh);
        }
         //Xóa
        [HttpGet]
        public ActionResult Xoa(int makh)
        {
            //Lấy ra đối tượng sp theo mã
            KHACHHANG kh = db.KHACHHANGs.SingleOrDefault(n => n.MaKH == makh);
            if (kh == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            return View(kh);
        }

        [HttpPost, ActionName("Xoa")]
        public ActionResult XacNhanXoa(int makh)
        {
            KHACHHANG kh = db.KHACHHANGs.SingleOrDefault(n => n.MaKH == makh);
            if (kh == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            db.KHACHHANGs.DeleteOnSubmit(kh);
            db.SubmitChanges();
            return RedirectToAction("DanhSachKhachHang");
        }
    }
}

WatchStore/Areas/Admin/Controllers/QlyPhanHoiController.cs
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WatchStore.Models;

namespace WatchStore.Areas.Admin.Controllers
{
    public class QlyPhanHoiController : Controller
    {
        dbQLBandhDataContext db = new dbQLBandhDataContext();
        // GET: Admin/QlyPhanHoi
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult DanhSachPhanHoi(string timkiem, int? page)
        {
            if (Session["Admin"] == null || Session["TaiKhoanAdmin"].ToString() == "")
            {
                return RedirectToAction("Login", "Authh");
            }
            ViewBag.TuKhoa = timkiem;
            int pageNumber = (page ?? 1);
            int pageSize = 5;
            if (timkiem != null)
            {

                List<LIENHE> listKQ = db.LIENHEs.Where(n => n.HoTen.Contains(timkiem)).ToList();
                if (listKQ.Count == 0)
                {
                    TempData["tb"] = "Không tìm thấy phản hồi nào phù hợp.";
                    return View(db.LIENHEs.OrderBy(n => n.HoTen).ToPagedList(pageNumber, pageSize));
                }
                return View(listKQ.OrderBy(n => n.MaLH).ToPagedList(pageNumber, pageSize));
            }
            return View(db.LIENHEs.OrderBy(n => n.MaLH).ToPagedList(pageNumber, pageSize));
        }
        //Chi tiết
      
        public ActionResult HienThiLH(int malh)
        {
            if (Session["Admin"] == null || Session["TaiKhoanAdmin"].ToString() == "")
            {
                return RedirectToAction("Login", "Authh");
            }
            //Lấy ra đối tượng sp theo mã
            LIENHE lh = db.LIENHEs.SingleOrDefault(n => n.MaLH == malh);
            if (lh == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            return View(lh);
        }
        public ActionResult ChiTiet(int malh, int? page)
        {
            TempData["Malh"] = malh;
            int pageNumber = (page ?? 1);
            int pageSize = 5;
            //Lấy ra đối tượng sp theo mã
            var listlienhe = db.LIENHEs.Where(n => n.MaLH == malh).OrderBy(n => n.MaLH).ToPagedList(pageNumber, pageSize);
            if (listlienhe == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            return View(listlienhe);
        }
    }
}

WatchStore/Areas/Admin/Controllers/QlySanPhamController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WatchStore.Models;
using PagedList;
using PagedList.Mvc;
using System.IO;


namespace WatchStore.Areas.Admin.Controllers
{
    public class QlySanPhamController : Controller
    {
        dbQLBandhDataContext db = new dbQLBandhDataContext();
        // GET: Admin/QlySanPham
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult QuanLySanPham(string timkiem, int? page)
        {
            if (Session["Admin"] == null || Session["TaiKhoanAdmin"].ToString() == "")
            {
                return RedirectToAction("Login", "Authh");
            }
            ViewBag.TuKhoa = timkiem;
            int pageNumber = (page ?? 1);
            int pageSize = 5;
            if (timkiem != null)
            {
                List<DONGHO> listKQ = db.DONGHOs.Where(n => n.TenDH.Contains(timkiem)).ToList();
                if (listKQ.Count == 0)
                {
                    TempData["tb"] = "Không tìm thấy sản phẩm nào phù hợp.";
                    return View(db.DONGHOs.OrderBy(n => n.TenDH).ToPagedList(pageNumber, pageSize));
                }
                return View(listKQ.OrderBy(n => n.MaSP).ToPagedList(pageNumber, pageSize));
            }
            return View(db.DONGHOs.OrderBy(n => n.MaSP).ToPagedList(pageNumber, pageSize));
        }
        [HttpGet]
        public ActionResult ThemMoi()
        {
            if (Session["Admin"] == null || Session["TaiKhoanAdmin"].ToString() == "")
            {
                return RedirectToAction("Login", "Authh");
            }
            ViewBag.TenNSX = new SelectList(db.NHASANXUATs.ToList().OrderBy(n => n.TenNSX), "MaNSX", "TenNSX");
            ViewBag.TenSP = new SelectList(db.DONGHOs.ToList().OrderBy(n => n.TenDH), "MaSP", "TenSP");
            ViewBag.TenChuDe = new SelectList(db.CHUDEs.ToList().OrderBy(n => n.TenChuDe), "MaCD", "TenChuDe");
            return View();
        }

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult ThemMoi(DONGHO sp, HttpPostedFileBase fileUpload, HttpPostedFileBase fileUpload2, HttpPostedFileBase fileUpload3)
        {
            int mansx = int.Parse(Request.Form["TenNSX"]);
            int macd = int.Parse(Request.Form["TenChuDe"]);
            ViewBag.TenChuDe = new SelectList(db.CHUDEs.ToList().OrderBy(n => n.TenChuDe), "MaCD", "TenChuDe");
            ViewBag.TenNSX = new SelectList(db.NHASANXUATs.ToList().OrderBy(n => n.TenNSX), "MaNSX", "TenNSX");
            if (fileUpload == null)
            {
                ViewBag.ThongBao = "Chọn hình ảnh";
                return View();
            }
            //Thêm vào cơ sở dữ liệu
            if (ModelState.IsValid)
            {
                //Lưu tên file
                var fileName = Path.GetFileName(fileUpload.FileName);
                var fileName2 = Path.GetFileName(fileUpload2.FileName);
                var fileName3 = Path.GetFileName(fileUpload3.FileName);
                //Lưu đường dẫn của file
                var path = Path.Combine(Server.MapPath("~/Content/images"), fileName);
                var path2 = Path.Combine(Server.MapPath("~/Content/images"), fileName2);
                var path3 = Path.Combine(Server.MapPath("~/Content/images"), fileName3);
                //Kiểm tra hình ảnh đã tồn tại chưa
                if (System.IO.File.Exists(path))
                {
                    ViewBag.ThongBao = "Hình ảnh đã tồn tại";
                }
                else
                {
                    fileUpload.SaveAs(path);
                }
                //Kiểm tra hình ảnh đã tồn tại chưa
                if (System.IO.File.Exists(path2))
                {
                    ViewBag.ThongBao = "Hình ảnh đã tồn tại";
                }
                else
                {
                    fileUpload2.SaveAs(path2);
                }
                //Kiểm tra hình ảnh đã tồn tại chưa
                if (System.IO.File.Exists(path3))
                {
                    ViewBag.ThongBao = "Hình ảnh đã tồn tại";
                }
                else
                {
                    fileUpload3.SaveAs(path3);
                }
                sp.Anhbia = fileUpload.FileName;
                sp.Anh1 = fileUpload2.FileName;
                sp.Anh2 = fileUpload3.FileName;
             
                //sp.NgayCapNhat = DateTime.Now;
                sp.MaCD = macd;
                sp.MaNSX = mansx;
                sp.Ngaycapnhat = DateTime.Now;
                db.DONGHOs.InsertOnSubmit(sp);
                db.SubmitChanges();
                TempData["thanhcong"] = "Thêm mới sản phẩm thành công!";
            }
            else
                TempData["kthanhcong"] = "Thêm sản phẩm thất bại";
            return View();
        }
        //Chỉnh sửa sản phẩm
        [HttpGet]
        public ActionResult ChinhSua(int masp)
        {
            if (Session["Admin"] == null || Session["TaiKhoanAdmin"].ToString() == "")
            {
                return RedirectToAction("Login", "Authh");
            }
            //Lấy ra đối tượng sp theo mã
            DONGHO sp = db.DONGHOs.SingleOrDefault(n => n.MaSP == masp);
         if (sp == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            //Đưa dữ liệu vào dropdownlist
            ViewBag.TenNSX = new SelectList(db.NHASANXUATs.ToList(), "MaNSX", "TenNSX", sp.MaNSX);
            ViewBag.TenCD = new SelectList(db.CHUDEs.ToList(), "MaCD", "TenChuDe", sp.MaCD);           
            return View(sp);
        }
        [HttpPost]
        [ValidateInput(false)]
        public ActionResult ChinhSua(DONGHO sp,HttpPostedFileBase mt, HttpPostedFileBase fileUpload3, HttpPostedFileBase fileUpload4, HttpPostedFileBase fileUpload5)
        {
            int a = sp.MaSP;
            int mansx = int.Parse(Request.Form["TenNSX"]);
            int soluong = int.Parse(Request.Form["Soluongton"]);
            int giaban = int.Parse(Request.Form["Giaban"]);
            //Đưa dữ liệu vào dropdownlist
            ViewBag.TenNSX = new SelectList(db.NHASANXUATs.ToList(), "MaNSX", "TenNSX", sp.MaNSX);
            ViewBag.TenCD = new SelectList(db.CHUDEs.ToList(), "MaCD", "TenChuDe", sp.MaCD);
            if (fileUpload3 ==null && fileUpload4 == null && fileUpload5 == null)
            {
                ViewBag.Thongbao = "Vui lòng chọn ảnh !!!";
                return View(sp);
            }
            //Thêm vào csdl
            else
            {
                if (ModelState.IsValid)
                {
                    var fileName3 = Path.GetFileName(fileUpload3.FileName);

                    var fileName4 = Path.GetFileName(fileUpload4.FileName);

                    var fileName5 = Path.GetFileName(fileUpload5.FileName);
                    //Lưu đường dẫn của file
                    var path3 = Path.Combine(Server.MapPath("~/Content/images"), fileName3);

                    var path4 = Path.Combine(Server.MapPath("~/Content/images"), fileName4);

                    var path5 = Path.Combine(Server.MapPath("~/Content/images"), fileName5);
                    //Kiểm tra hình ảnh đã tồn tại chưa
                    if (System.IO.File.Exists(path3))
                    {
                        ViewBag.ThongBao = "Hình ảnh đã tồn tại";
                    }
                    else
                    {
                        fileUpload3.SaveAs(path3);
                    }
                    //Kiểm tra hình ảnh đã tồn tại chưa
                    if (System.IO.File.Exists(path4))
                    {
                        ViewBag.ThongBao = "Hình ảnh đã tồn tại";
                    }
                    else
                    {
                        fileUpload4.SaveAs(path4);
                    }
                    //Kiểm tra hình ảnh đã tồn tại chưa
                    if (System.IO.File.Exists(path5))
                    {
                        ViewBag.ThongBao = "Hình ảnh đã tồn tại";
                    }
                    else
                    {
                        fileUpload5.SaveAs(path5);
                    }
                    DONGHO sp2 = db.DONGHOs.Where(n => n.MaSP ==a).SingleOrDefault();
                    string anh1 = fileName3;
                    string anh2 = fileName4;
                    string anh3 = fileName5;
                    //Thực hiện cập nhật trong model
                    sp2.Anhbia =anh1;
                    sp2.Anh1 = anh2;
                    sp2.Anh2 = anh3; 
                    sp2.Ngaycapnhat = DateTime.Now;
                    sp2.MaDH = Request.Form["MaDH"];
                    sp2.TenDH= Request.Form["TenDH"];
                    sp2.Chatlieu = Request.Form["Chatlieu"];
                    sp2.Giaban = giaban;
                    sp2.Soluongton = soluong;
                    //sp2.Mota = Request.Form["MoTa"];

                    //Lưu vào csdl
                    UpdateModel(sp2);
                    db.SubmitChanges();
                    TempData["thanhcong"] = "Chỉnh sửa sản phẩm thành công!";
                    return RedirectToAction("QuanLySanPham");
                }
                else
                {
                    TempData["kthanhcong"] = "Chỉnh sửa thất bại!";
                }   
            }
            return View();
        }
        public ActionResult HienThi(int masp)
        {
            //Lấy ra đối tượng sp theo mã
            DONGHO sp = db.DONGHOs.SingleOrDefault(n => n.MaSP == masp);
            if (sp == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            return View(sp);
        }
        public ActionResult ChiTiet(int masp, int? page)
        {
            TempData["Masp"] = masp;
            int pageNumber = (page ?? 1);
            int pageSize = 5;

WatchStore/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml
@using WatchStore.Models
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>@ViewBag.Title</title>
    <!-- Bootstrap Core CSS -->
    <link href="~/Content/Admin/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <!-- MetisMenu CSS -->
    <link href="~/Content/Admin/vendor/metisMenu/metisMenu.min.css" rel="stylesheet">
    <!-- Custom CSS -->
    <link href="~/Content/Admin/dist/css/sb-admin-2.css" rel="stylesheet">
    <!-- Morris Charts CSS -->
    <link href="~/Content/Admin/vendor/morrisjs/morris.css" rel="stylesheet">
    <!-- Custom Fonts -->
    <link href="~/Content/Admin/vendor/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <!-- DataTables CSS -->
    <link href="~/Content/Admin/vendor/datatables-plugins/dataTables.bootstrap.css" rel="stylesheet">
    <!-- DataTables Responsive CSS -->
    <link href="~/Content/Admin/vendor/datatables-responsive/dataTables.responsive.css" rel="stylesheet">
    <!--icon-->
    @*<link href="~/Content/NguoiDung/fontawesome-free-5.0.13/web-fonts-with-css/css/fontawesome.min.css" rel="stylesheet" />*@
    <script src="~/Content/NguoiDung/fontawesome-free-5.0.13/svg-with-js/js/fontawesome.min.js"></script>
    <link href="~/Content/NguoiDung/fontawesome-free-5.0.13/web-fonts-with-css/css/fontawesome-all.min.css" rel="stylesheet" />
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
            <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
            <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>

        <![endif]-->
    <!--Chèn thư viện ckfider-->
    <script src="~/Content/Admin/js/ckfinder/ckfinder.js"></script>

    <script src="~/Content/Admin/tinymce/js/tinymce/tinymce.min.js"></script>
    <script>tinymce.init({ selector: 'textarea' });</script>
    <style>
        body {
            background-image: url('../../Content/images/gradient_bg.png');
            background-repeat: repeat-x;
        }
    </style>
</head>
<body>
    <div id="wrapper">
        <!-- Navigation -->
        <nav class="navbar navbar-default navbar-static-top" role="navigation" style="background-color: #34495e;margin-bottom: 0">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="@Url.Action("Index", "ThongKe")" style="color:aliceblue">JOHN WICH WATSTORE AREAS</a>
            </div>
            <!-- /.navbar-header -->
            @if (Session["TaikhoanAdmin"] != null)
            {
                <ul class="nav navbar-top-links navbar-right">
                    <!-- /.dropdown -->
                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                            <i class="fa fa-user fa-fw"></i> <i class="fa fa-caret-down"></i>
                        </a>
                        <ul class="dropdown-menu dropdown-user">
                            <li>
                                <a href="#">
                                    <i class="fa fa-user fa-fw"></i>
                                    @if (Session["Admin"] != null)
                                    {
                                        <span>@Session["Admin"].ToString()</span>
                                    }
                                </a>
                            </li>
                            @*<li>
                                    <a href="#"><i class="fa fa-gear fa-fw"></i> Settings</a>
                                </li>*@
                            <li class="divider"></li>
                            <li>
                                <a href="@Url.Action("Logout", "Authh")"><i class="fa fa-sign-out fa-fw"></i>Logout</a>
                            </li>
                        </ul>
                        <!-- /.dropdown-user -->
                    </li>
                    <!-- /.dropdown -->
                </ul>
            }

            <!-- /.navbar-top-links -->
            <div class="navbar-default sidebar" role="navigation">
                <div class="sidebar-nav navbar-collapse">
                    <ul class="nav" id="side-menu">
                        <li>
                            <a href="@Url.Action("Index","ThongKe")"><i class="fa fa-dashboard"> </i>  Thống kê</a>
                        </li>
                        <li>
                            <a href="#"><i class="fa fa-file-text"></i>  Quản lý sản phẩm<span class="fa arrow"></span></a>
                            <ul class="nav nav-second-level">
                                <li>
                                    <a href="@Url.Action("QuanLySanPham", "QlySanPham")"><i class="fa fa-list-alt"></i> Sản phẩm</a>
                                </li>
                            </ul>
                            
                        </li>
                        <li>
                            <a href="#"><i class="fa fa-user"></i> Khách hàng <span class="fa arrow"></span></a>
                            <ul class="nav nav-second-level">

                                <li>
                                    <a href="@Url.Action("DanhSachKhachHang","QlyKhachHang")"><i class="fa fa-users"></i> Danh sách khách hàng</a>
                                </li>

                                <li>
                                    <a href="@Url.Action("DanhSachPhanHoi","QlyPhanHoi")"><i class="fa fa-comments"></i> Phản hồi</a>
                                </li>
                            </ul>
                            <!-- /.nav-second-level -->
                        </li>
                        <li>
                            <a href="#"><i class="fa fa-list"></i> Đơn hàng <span class="fa arrow"></span></a>
                            <ul class="nav nav-second-level">
                                <li>
                                    <a href="#"><i class="fa fa-sign-out"></i> Xuất hàng<span class="fa arrow"></span></a>
                                    <ul class="nav nav-second-level">
                                        <li>
                                            <a href="@Url.Action("DanhSachDonHang","QlyDonHang")"><i class="fa fa-th-list"></i> Danh sách đơn hàng</a>
                                        </li>
                                        <li>
                                            <a href="@Url.Action("DanhSachChuaDuyet","QlyDonHang")"><i class="fa fa-magic"></i> Chờ duyệt</a>
                                        </li>
                                        <li>
                                            <a href="@Url.Action("DonHangChoGiao","QlyDonHang")"><i class="fa fa-truck"></i> Chờ giao</a>
                                        </li>
                                    </ul>
                                </li>
                                <li>
                                    <a href="#"><i class="fa fa-sign-in"></i> Nhập hàng<span class="fa arrow"></span></a>
                                    <ul class="nav nav-second-level">
                                        <li>
                                            <a href="@Url.Action("DanhSachPhieuNhap","QlyNhapHang")"><i class="fa fa-th-list"></i> Danh sách phiếu nhập</a>
                                        </li>
                                        @*<li>
                                                <a href="@Url.Action("DanhSachChuaDuyet","QlyDonHang")"><i class="fas fa-users"></i> Chờ duyệt</a>
                                            </li>*@
                                    </ul>
                                </li>
                            </ul>
                            <!-- /.nav-second-level -->
                        </li>
                    </ul>
                </div>
                <!-- /.sidebar-collapse -->
            </div>
            <!-- /.navbar-static-side -->
        </nav>
        <div id="page-wrapper">
            @RenderBody()
        </div>
        <!-- /#page-wrapper -->
    </div>
    <!-- /#wrapper -->
    <!-- jQuery -->
    <script src="~/Content/Admin/vendor/jquery/jquery.min.js"></script>
    <!-- Bootstrap Core JavaScript -->
    <script src="~/Content/Admin/vendor/bootstrap/js/bootstrap.min.js"></script>
    <!-- DataTables JavaScript -->
    <script src="~/Content/Admin/vendor/dataTablestables/js/jquery.dataTables.min.js"></script>
    <script src="~/Content/Admin/vendor/datatables-plugins/dataTables.bootstrap.min.js"></script>
    <script src="~/Content/Admin/vendor/datatables-responsive/dataTables.responsive.js"></script>
    <!-- Metis Menu Plugin JavaScript -->
    <script src="~/Content/Admin/vendor/metisMenu/metisMenu.min.js"></script>
    <!-- Morris Charts JavaScript -->
    <script src="~/Content/Admin/vendor/raphael/raphael.min.js"></script>
    <script src="~/Content/Admin/vendor/morrisjs/morris.min.js"></script>
    <script src="~/Content/Admin/data/morris-data.js"></script>
    <!--add js ckfinder va ckeditor-->
    <script src="~/Content/Admin/js/plugins/ckfinder/ckfinder.js"></script>
    <script src="~/Content/Admin/js/plugins/ckeditor/ckeditor.js"></script>
    <!-- Custom Theme JavaScript -->
    <script src="~/Content/Admin/dist/js/sb-admin-2.js"></script>

</body>
</html>